# Generated by Django 3.0 on 2024-03-27 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_comments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="object_id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "object_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
