# Generated by Django 2.2.17 on 2021-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
    ]

