name: Pull Request tests

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        django:
          - django-22
          - django-30
          - django-31
          - django-32
        # https://docs.djangoproject.com/en/3.2/faq/install/#what-python-version-can-i-use-with-django
        exclude:
          - django: django-22
            python: 3.9
          - django: django-30
            python: 3.5
          - django: django-31
            python: 3.5
          - django: django-32
            python: 3.5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install -r requirements_test.txt
      - name: Run Tox
        run: tox -e py-${{ matrix.django }}
# Codecov is running separately?
#      - name: Codecov
#        run:  codecov -e ${{ matrix.python }}-${{ matrix.django }}
